# Generated by Django 6.0 on 2026-01-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(default='fas fa-trophy', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID')),
                ('team1', models.CharField(max_length=200, verbose_name='Команда 1')),
                ('team2', models.CharField(max_length=200, verbose_name='Команда 2')),
                ('team1_logo', models.CharField(blank=True, max_length=500, verbose_name='Логотип команды 1')),
                ('team2_logo', models.CharField(blank=True, max_length=500, verbose_name='Логотип команды 2')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('league', models.CharField(max_length=200, verbose_name='Лига/Турнир')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('coefficient_team1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент 1')),
                ('coefficient_team2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент 2')),
                ('coefficient_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Коэффициент ничьи')),
                ('total_over', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Тотал больше')),
                ('total_under', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Тотал меньше')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('live', 'В прямом эфире'), ('finished', 'Завершен'), ('cancelled', 'Отменен')], default='upcoming', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен для ставок')),
                ('result', models.CharField(blank=True, max_length=50, verbose_name='Результат')),
                ('score', models.CharField(blank=True, max_length=20, verbose_name='Счет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.sport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['sport', 'start_time'], name='matches_mat_sport_i_457526_idx'), models.Index(fields=['status', 'is_active'], name='matches_mat_status_7bf13f_idx')],
            },
        ),
    ]
