# Generated by Django 6.0 on 2026-01-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод'), ('bet', 'Ставка'), ('win', 'Выигрыш'), ('refund', 'Возврат'), ('bonus', 'Бонус')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('failed', 'Неудачная'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('qiwi', 'QIWI'), ('yoomoney', 'ЮMoney'), ('webmoney', 'WebMoney'), ('crypto', 'Криптовалюта'), ('bank_transfer', 'Банковский перевод')], max_length=50, verbose_name='Способ оплаты')),
                ('payment_details', models.JSONField(blank=True, default=dict, verbose_name='Детали платежа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Внешний ID транзакции')),
                ('bank_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.bet', verbose_name='Ставка')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
