# Generated by Django 6.0 on 2026-01-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('team1', 'Победа первой команды'), ('team2', 'Победа второй команды'), ('draw', 'Ничья'), ('total_over', 'Тотал больше'), ('total_under', 'Тотал меньше')], max_length=20, verbose_name='Тип ставки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потенциальный выигрыш')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('won', 'Выиграна'), ('lost', 'Проиграна'), ('cancelled', 'Отменена'), ('returned', 'Возвращена')], default='pending', max_length=20, verbose_name='Статус')),
                ('result_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактический выигрыш')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата расчета')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-created_at'],
            },
        ),
    ]
