# Generated by Django 6.0 on 2026-01-04 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status'], name='bets_bet_user_id_f8a082_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['match', 'status'], name='bets_bet_match_i_4b6c98_idx'),
        ),
    ]
